# -*- coding: utf-8 -*-
"""cancer_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bw8u3jM-GOUcL-9AyqR1dDD53hfj4SA8

#**Cancer Patients Analysis**

###**1. Import libraries**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""###**2. Load dataset**"""

df= pd.read_csv('/content/cancer_patients_dataset.csv')

df

"""###**3. Exploratory analysis**"""

df.head()

df.tail()

df.info()

df.sample(5)

df.describe()

df.shape

df.Country_Region.unique()

df.Cancer_Type.unique()

"""###**4. Data cleaning**"""

df.isnull().sum()

df.duplicated().sum()

"""###**5. Analysis & visualization**

###Gender distribution
"""

gender_count = df.groupby('Gender').size()

plt.figure(figsize=(6, 5))
gender_count.plot(kind='pie', startangle=90 , autopct='%1.1f%%')
plt.title('Gender distribution of patients')
plt.legend()
plt.tight_layout()
plt.show()

"""###Age distribution"""

age= df.Age

plt.figure(figsize=(8,6))
age.plot(kind='hist' , bins=15 , edgecolor='black')
plt.title('Distribution of Cancer Patients by Age')
plt.xlabel('Age')
plt.ylabel('Number of Patients')
plt.ylim(0,4000)
plt.tight_layout()
plt.show()

"""###Top countries with highest cancer patients"""

top_country = df['Country_Region'].value_counts().head(5)

top_country.sort_values().plot(kind='barh', edgecolor='black')
plt.title('Top 5 countries')
plt.xlabel('Number of patients')
plt.ylabel('Country')
plt.tight_layout()
plt.show()

"""###Top cancer types"""

cancer_types = df.Cancer_Type.value_counts().head(3)

cancer_types.plot(kind='bar', edgecolor='black')
plt.title('Top Cancer Types')
plt.xlabel('Cancer Type')
plt.xticks(rotation=45)
plt.ylabel('Number of patients')
plt.tight_layout()
plt.show()

"""###Avg Treatment Cost by Cancer Type and Stage"""

cost_by_type_stage =df.groupby(['Cancer_Type', 'Cancer_Stage'])['Treatment_Cost_USD'].mean().unstack()

cost_by_type_stage.plot(kind='bar', figsize=(8,6))
plt.title("Avg Treatment Cost by Cancer Type and Stage")
plt.xlabel("Cancer Type")
plt.ylabel("Avg Cost (USD)")
plt.ylim(0,60000)
plt.xticks(rotation=45)
plt.tight_layout()
plt.legend(title='Cancer Stage', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

"""###Avg survival rate by cancer stage"""

avg_survial = df.groupby('Cancer_Stage')['Survival_Years'].mean().sort_index()

avg_survial.plot(kind='bar', edgecolor='black')
plt.title("Avg Survival Years by Cancer Stage")
plt.xlabel("Cancer Stage")
plt.ylabel("Survival Years")
plt.ylim(0,6)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""###Trends Over Time: Avg Treatment Cost"""

yearly_trends = df.groupby('Year')['Treatment_Cost_USD'].mean()
yearly_trends.plot(marker='o')
plt.title("Yearly Trends: AVG Treatment Cost")
plt.xlabel("Year")
plt.ylabel("Average Values")
plt.grid(True)
plt.tight_layout()
plt.show()

"""###Top 5 countries by avg treatment cost"""

cost_by_country = df.groupby('Country_Region')['Treatment_Cost_USD'].mean().sort_values(ascending=False).head(5)
cost_by_country.plot(kind='bar')
plt.title("Top 5 Countries by Avg Treatment Cost")
plt.xlabel("Avg Cost (USD)")
plt.ylabel("Country")
plt.ylim(0,60000)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""###Yearly Trend Patients Count"""

Yearly_trend_patients =df.groupby('Year')['Patient_ID'].size()

Yearly_trend_patients.plot(marker='o')
plt.title('Yearly Trend Patients Count')
plt.xlabel('Year')
plt.ylabel('Number of patients')
plt.ylim(0,10000)
plt.grid(True)
plt.tight_layout()
plt.show()